config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'}
  resources :users
  get '/users/:user_id/memes', to: 'users#index', as: 'user_memes'
  resources :memes do
      resources :comments
  end
  resources :comments
  get '/safe_for_work_memes', to: 'memes#safe_for_work', as: 'safe_for_work_memes'
  root 'memes#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :meme
    belongs_to :user
    validates :content, presence: true, allow_blank: false
    default_scope { order(created_at: :asc) }



end

app/models/meme.rb
class Meme < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :users, through: :comments
    validates :title, presence: true, allow_blank: false, format: {
        with: %r{\.(gif|jpe?g|png)\z}i,
        message: 'must link to a GIF, JPG, or PNG image'}
    validates :description, presence: true, allow_blank: false
    scope :safe_for_work, -> { where(nsfw: false) }
    default_scope { order(created_at: :desc) }
    accepts_nested_attributes_for :comments


end

app/models/user.rb
class User < ApplicationRecord
    has_many :comments
    has_many :memes, through: :comments
    devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
    
  
  # def create_username
  #   current_user.username = current_user.email[/[^@]+/]
  # end

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end    
  end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?


  




  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end



    def after_sign_in_path_for(resource)
        request.env['omniauth.origin'] || root_path
    end

   

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment_meme, only: [:new, :create, :edit, :update, :destroy]


    def new
        @comment = Comment.new   
    end

    def create
        if params[:meme_id]
            @comment = @meme.comments.build(content: params[:comment][:content], user_id: current_user.id)
        else 
            @comment = Comment.new(comment_params)
        end
        if @comment.save
            redirect_to @meme
        else
            flash[:notice] = "Your comment can't be blank."
            redirect_to new_meme_comment_path
        end
    end

    def edit
        @comment = @meme.comments.find_by(id: params[:id])
    end

    def update
        @comment = @meme.comments.find_by(id: params[:id])
            if @comment.user_id == current_user.id && @comment.save
                @comment.update(comment_params)
                redirect_to @meme
            else
                flash[:notice] = "You did something wrong. Of course."
                redirect_to edit_comment_path(@comment, meme_id: @meme.id)
            end
    end

    def destroy
        @comment = Comment.find_by(id: params[:id])
        if @comment.user_id == current_user.id
            @comment.destroy
            redirect_to @meme
        else
            flash[:notice] = "Could not delete that comment. Sorry."
            redirect_to meme_path(@meme.id)
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :meme_id, :user_id)
    end

    def set_comment_meme
        @meme = Meme.find_by(id: params[:meme_id])
    end

end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
    before_action :set_meme, only: [:show, :edit, :update, :destroy]
    

    def index
        @memes = Meme.all
    end

    def safe_for_work
        @memes = Meme.all.safe_for_work
        render :index
    end

    def new
        @meme = Meme.new
    end

    def create
        @meme = Meme.create(title: params[:meme][:title], description: params[:meme][:description], nsfw: params[:meme][:nsfw], user_id: current_user.id)
        if @meme.save
            redirect_to @meme
        else
            flash[:notice] = @meme.errors.full_messages.to_sentence
            render :new
        end
    end

    def edit
    end

    def show
        @comment = Comment.new
        if @meme
            render :show
        else
            flash[:notice] = "Meme not found"
            redirect_to memes_path
        end
    end

    def destroy
        if @meme.user_id == current_user.id && @meme.destroy
            redirect_to memes_path
        else
            flash[:notice] = "Could not delete that meme. Sorry."
            redirect_to @meme
        end
    end

    private

    def set_meme
        @meme = Meme.find_by(id: params[:id])
    end

    def meme_params
        params.require(:meme).permit(:title, :nsfw, :user_id, :description)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
    
  
  
  
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @memes = Meme.where(user_id: current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/meme_helper.rb
module MemeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<br>    
    <div class= "text-center">
        <h1> Got something to say? </h1>
    </div>
<br>
    <h2> <%= flash[:notice] %> </h2>
<br>
    <div class= "text-center">
        <%= image_tag (@meme.title) %>
    </div>
<br>
<br>
    <%= form_for [@meme, @comment] do |f| %>
        <br>
        <div class= "text-center">
            <%= f.text_area :content, size: "75x10", placeholder: "Start a fight" %>
        <div>
        <br>
        <div class= "text-center">
            <%= f.submit %>
        </div>
    <% end %>
<br>
<br>

app/views/comments/edit.html.erb
<%= render "form" %>

app/views/comments/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Politibro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <p class="navbar-brand">
  <% if current_user.present? %>
    <%= link_to current_user.email[/[^@]+/], user_memes_path(current_user.id), method: :get %>
  <% else %>
    <p>Politibro   </p>
  <% end %>
  </p>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=destroy_user_session_path%>">Sign Out</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=new_meme_path%>">Create New Meme</a>
      </li>
    </ul>
  </div>
</nav>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_with model: @meme, local: :true do |form| %>
  <div class= "text-center">
    <%= form.label :title, "Insert image location/url here: " %>
    <br>
    <%= form.text_field :title, size: "30x10", class: @meme.errors.any? ? "custom_errors" : nil %>
  </div>
<br>
<br>
  <div class= "text-center">
    <%= form.label :description, "Please include a description of this meme: " %>
    <br>
    <%= form.text_area :description, size: "75x10", style: "white-space: pre-wrap" %>
  </div>
<br>
  <div class = "text-center">
  <%= form.label :nsfw, "Could this image be considered offensive or unsafe for work environments? " %>
  <br>
  <td><%= form.select :nsfw, options_for_select([['Yes', true], ['No', false]])%></td>
  </div>
<br>
<br>
  <div class= "text-center">
    <%= form.submit %>
  </div>
<% end %>

app/views/memes/index.html.erb
<div class= "text-center"> <h1>P O L I T I B R O</h1> </div>
<br>
<br>
  <div class="text-center">
    <h3> Here are some of our freshest memes: </h3>
  </div>
<br>

<div class= "text-center">
<small> <%= link_to "Hide Inappropriate Memes", safe_for_work_memes_path %> </small>
</div>

<br>
 <% if flash[:notice] %>
    <% flash[:notice] %>
<% end %>
<br>

<div class="card-deck">
<% @memes.each do |meme| %>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%=meme.title%>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"><%= link_to meme.description, meme_path(meme.id) %> </h5>
    <p class="card-text"><small class="text-muted"> Posted: <%= meme.created_at.strftime("%B %d %Y, %l:%M%P") %> </small></p>
    <a href="<%= meme_path(meme.id) %>" class="btn btn-primary">Go</a>
  </div>
</div>
<% end %>
</div>


app/views/memes/new.html.erb
<div class= "text-center"><h1>Post a new Meme: </h1></div>
<br>
<h3> <%= flash[:notice] %> </h3>
<%= render "form" %>

app/views/memes/show.html.erb
<head>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<br>
<body>

    <div class="text-center">
    <img src="<%= (@meme.title) %>" class="rounded" alt="Probably a dumb meme was here">
    </div>
<br>

    <div class="text-center">
    <% if @meme.user %>
    <small class> Created by: <%= @meme.user.email[/[^@]+/] %> </small>
    <% else %>
    <small class> Created by: Anonymous </small>
    <% end %>
<br>
<br>
    <h3> <%= @meme.description %> </h3>
<br>
<br>    
    </div>

    <div class="text-center">
    <%= button_to "New Comment", new_meme_comment_path(@meme.id), method: :get %>
    </div>
<br>
    <div class="text-center">
    <% if @meme.user_id == current_user.id %>
    <%= button_to "Delete This Meme", meme_path(@meme), method: :delete, data: {confirm: 'Are you sure you want to delete this "hilarious" meme?'} %>
    <% end %>
    </div>
<br>
<br>

<div class="container">
    <div class="page-header">
        <h1><small class="pull-right"><%= @meme.comments.count %> </small> Comments </h1>
    </div> 
        <% @meme.comments.each do |comment|%>
                <div class="row">
                    <div class="col-md-8">
                        <div class="comments-list">
                            <div class="media">
                                <p class="pull-right"></p>
                                    <a class="media-left" href="#">
                                    </a>
                                    <div class="media-body">
                                    <h3 class="media-heading user_name"><%= comment.user.email[/[^@]+/] %> says:</h3>
                                    <h4> <%= comment.content %> </h4>
                                    <p><small>posted: <%= comment.created_at.strftime("%B %d %Y, %l:%M%P") %></small></p>
                                        <% if comment.user_id == current_user.id %> 
                                        <p> <%= link_to "Delete", comment_path(comment, meme_id: @meme.id), method: :delete %> - <%= link_to "Edit", edit_comment_path(comment, meme_id: @meme.id), method: :get %> </p>
                                        <% end %>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
        <% end %>
</div>
<br>
<br>
<br>
</body>

app/views/users/index.html.erb
<div class= "text-center">
  <h2> Here are all of your memes: </h2>
</div>
<br>
<br>
  <div class="card-deck">
    <% @memes.each do |meme| %>
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%=meme.title%>" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title"><%= link_to meme.description, meme_path(meme.id) %> </h5>
          <p class="card-text"><small class="text-muted"> Posted: <%= meme.created_at.strftime("%B %d %Y, %l:%M%P") %> </small></p>
          <a href="<%= meme_path(meme.id) %>" class="btn btn-primary">Go</a>
        </div>
      </div>
    <% end %>
  </div>